homelab_domain: ENC[AES256_GCM,data:jtoAh7LAJ4wK,iv:rrYMDZCoW7WKz6rJTRTaXu+lOyYblxmTGVT83N7dXz4=,tag:y6YcRMYaM3uaZo4D1/6mdg==,type:str]
acme_email: ENC[AES256_GCM,data:98J8thy5gQ+SmjFIOjis,iv:2dhx581e8d8idecKCia9MiPwgDa+bqqv7N1OqmXA/jA=,tag:1StUhzcxQBumqkx0gpHw0Q==,type:str]
edge_restic_offsite_repo: ENC[AES256_GCM,data:yFVoNYaZpRkecM8jxhE7mFSMSpMuDcVZrCitiROf3/zI1hMpP2kN1gTYSZFZtMOY,iv:1SJh1iEEt0OdCzmCN1XVNB8z4JEwBZcEuW0gh0T9diI=,tag:I8rjRt0ZRBAY14gC9B4giA==,type:str]
vps_ipv4: ENC[AES256_GCM,data:vOXr3ZXIHto11ytn7Aq0SOA=,iv:t+2KeXq9guOqHpDq4cjAi5V5YXGjWrvZEdjs1x3t+sA=,tag:B9kucYx2BMU0iXLAR4FErw==,type:str]
vps_ipv6: ENC[AES256_GCM,data:ssE36sp9/eIxCb+bwXOm4NrrgVOBz+7uov8QDIG78wnPnDY=,iv:CO9UBZoqXf1xNHxP3Z7uC+cJEaDqMB1hfbrpsVmvGbk=,tag:h2E1PORZWiwo/e6Hh1px3A==,type:str]
secondary_domain: ENC[AES256_GCM,data:aybObRzSeA==,iv:uoRq+UTr3Zy2pdUhujGA7BNP1y3WupluXeOHxR6+Cgg=,tag:Q6Jbh+y2DLTWhmVILYCBcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQkRiTzZWSUNvR2ZmSmpK
            Z2k1NjBNTDNBN1RIaityZTNiT0NzQ2tGdFhZClFzb2dTRFgrZTNRUmN1YWdyWEs4
            SktRbmc3ZmY3bWZQQ2FEU3VrbkhZbmcKLS0tIFI4K1Y2bmdNcVppNy9kc1lJRHVF
            RXVjL0w1TDVzc0ZtdnZTOGpnNXM1TUkKn90e0sb8lXVrp9S7AkiiKJXfFeh/35l0
            foE+kGoHegnKIbwxoIdKNzs3nkiaNNR8h3pNwXMKBUFt5owGUWju7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rtp96zhxs6dwnx5c0xqanf2aamfkgmkntdakn95z3efglcyvhdvs0zzsn4
    lastmodified: "2026-07-04T17:12:07Z"
    mac: ENC[AES256_GCM,data:rh/EJOwNVPoc9/FdGe3vn4CiAa4YCCYa5p2jLNm9sAAAaqsaLncs/zTlipP0SLJzZhkrLYUn0m7PPjc70zFOurXgmWW6sibhAF8cGu3h8qLoB24DAnn/qjIp0VDN8RAbyxELsA+YnunxtlM93IqQthr1Fr9rL+RntKGm+yzOB1E=,iv:+m+rPPfgLEYX2uyyxkjyVQ/cWeo5vHm4szI7pGjDNwY=,tag:lOVzvBCRopL5GdHmI6AndQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
